---

name: Do reachability tests
on:
  workflow_dispatch:
  push:
    paths:
      - "src/kemtls/model/**"
      - "src/kemtls/test/**"
      - ".github/workflows/reachability.yaml"
    branches:
      - kem-auth

jobs:
  reachability:
    runs-on: ubuntu-latest
    steps:
      - name: Record homebrew cache location
        run: "echo '::set-output name=CACHE_DIR::'$(brew --cache)"
        id: cache_path
      - name: Cache homebrew stuffs
        uses: actions/cache@v2
        with:
          path: ${{ steps.cache_path.CACHE_DIR }}
          key: ${{ runner.os }}-homebrew
      - name: Install tamarin
        run: |
          brew install tamarin-prover/tap/tamarin-prover
      - uses: actions/checkout@v2
      - name: Run reachability tests
        run: |
          make test
        working-directory: src/kemtls/tests
